# Generated by Django 5.2.1 on 2025-05-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pregunta_participante_opcion_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('Etapa 1', 'Etapa 1'), ('Etapa 2', 'Etapa 2'), ('Etapa 3', 'Etapa 3'), ('Etapa 4', 'Etapa 4'), ('Etapa 5', 'Etapa 5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.participante')),
            ],
        ),
    ]
